import { Footer } from "@/components/layout-components/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function InventoryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <div id="portal" />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
